### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by ngaumont** [medialab/datapol#17]
Hi,

The website is beautiful but it's not display properly with Firefox
As I don't know angular, I wasn't able to find a fix.

Noé

**Comment by Yomguithereal** [comment]
Hello @ksadorf. There is indeed a bug in the layout when using Firefox. Can't find its origin though. Any idea @jacomyma?

**Comment by jacomyma** [comment]
You're right! It looks like a compatibility issue between flex and Firefox's last version. It's now fixed. Thanks!
